### ISSUE TITLE
warnings following steps from readme

### ISSUE THREAD

**Issue by jorgepz** [PetrKryslUCSD/FinEtoolsFlexStructures.jl#1]
Hi, I propose including (unless I did not see them in other place) a brief text in the Readme with basic steps for using the package or running the tests.

**Comment by jorgepz** [comment]
I am trying to run it following https://pkgdocs.julialang.org/v1/environments/
```
$ julia
]
pkg> activate .
pkg> instantiate
```
got this error

```julia
(FinEtoolsFlexStructures) pkg> instantiate
ERROR: TypeError: in typeassert, expected VersionNumber, got a value of type Pkg.Types.VersionSpec
Stacktrace:
  [1] load_urls(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:545
  [2] #download_source#57
    @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:732 [inlined]
...
```

**Comment by jorgepz** [comment]
got the same error using
```julia
julia> include("top.jl")
```

**Comment by PetrKryslUCSD** [comment]
Which version? The project was created with Julia 1.6 and works with 1.7 and up.

**Comment by PetrKryslUCSD** [comment]
Thanks for the comment. Documentation is at this point under intensive development.

**Comment by jorgepz** [comment]
that was the reason! i executed it using v 1.6.3, now using 1.7.0. I got a few warnings
```julia
┌ Warning: Could not use exact versions of packages in manifest, re-resolving
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/Pkg/src/Operati
```
and this other general one
```julia
┌ Warning: The active manifest file is an older format with no julia version entry. Dependencies may have been resolved with a different julia version.
└ @ ~/work/jorgepz/codigos/FinEtoolsFlexStructures.jl_repo/
```
but was able to install it anyway. is there a reason for versioning the manifest file?

**Comment by PetrKryslUCSD** [comment]
Good question. I always version the Manifest.toml. I like to have precisely the same environment every time
I clone the package.

**Comment by jorgepz** [comment]
Ah ok. Then the warnings are explained, thus i close the issue and the PR.

**Comment by jorgepz** [comment]
Thanks for the comments/help!

**Comment by PetrKryslUCSD** [comment]
Many thanks for your comments. Don't hesitate to get in touch.
